### PR TITLE
A few quality of life updates

### PR DESCRIPTION
**Pull request by victorprocure**
- Updated to support .NET core 3.0
- Streamlined build using paket and a new version of csproj files
- Added a Mode ability to select the style of indicator, so the user doesn't have to include default styles
- Add directory build props and targets to allow easier packing for nuget

### CODE REVIEW

**Comment by zeluisping** [comment]
Will be reviewing this once I have time! In the meantime people who want to use that version can just close and build from your `master`

Thank you so much for the collaboration!

**Comment by punker76** [comment]
@zeluisping LGTM 👍 

Only one point. Do we need these new headers?

https://github.com/zeluisping/LoadingIndicators.WPF/pull/6/files#diff-af5281d7cedd6721c379eb1efa72eb19R2-R4

**Comment by zeluisping** [comment]
@punker76 Can you explain what you mean by new headers? The link you provided is giving me the diff of the whole pull request and I'm not quite sure where to look at, specially since I am not up-to-date with modern C# practices

**Comment by punker76** [comment]
> @punker76 Can you explain what you mean by new headers? The link you provided is giving me the diff of the whole pull request and I'm not quite sure where to look at, specially since I am not up-to-date with modern C# practices

Sorry, here is a better link...

https://github.com/zeluisping/LoadingIndicators.WPF/blob/03fc84e426a5e632b080ddadc3fdcfd8c239834b/src/LoadingIndicators.WPF/IndicatorVisualStateGroupNames.cs#L1-L9

**Comment by zeluisping** [comment]
@victorprocure Would it be possible to remove these copyright headers? I want to keep everything in this repo under **The Unlicense** and by including that copyright this repo would now have code falling under two different licenses. I'm not asking this trying to disrespect your work, I greatly appreciate your contribution, but I'd like to keep it all under The Unlicense.

**Comment by victorprocure** [comment]
Yeah, thats my bad, CodeMaid added them in, thought I got them out. I'll do it when I'm home

**Comment by zeluisping** [comment]
Thought that would be the case, it's all good, remove it and then we'll proceed with the merge!

**Comment by sigmarsson** [comment]
Hi 
Will you accept this merge into the master ?
I wish to commit some changes too to add progress information.

**Comment by zeluisping** [comment]
Hey @sigmarsson, I'm just waiting on @victorprocure to remove that copyright, I'll make a pull request to his fork to see if that'll be faster. Thank you for wanting to contribute!

**Comment by victorprocure** [comment]
Sorry for the delay, been crazy busy. Hope thats good

**Comment by xzessmedia** [comment]
@zeluisping please merge, looks fine!

**Comment by zeluisping** [comment]
Will merge this tonight then! @xzessmedia thank you for the heads up

**Comment by brian-pickens-web** [comment]
Looking forward to the nuget package!

**Comment by PSharp93** [comment]
@zeluisping Could you publish the latest master to NuGet? That would be great, thank you in advance!

**Comment by zeluisping** [comment]
I'll try to do this at some point, I've just merged #13 and would include that too. There's issue #15 to release a new version to NuGet (after closing the other issues).

If anyone wants to contribute, feel free to. I'll try to put some time into it, but I can't guarantee anything.

**Pull request merged**
